$ANSIBLE_VAULT;1.1;AES256
35613638633036346635333830336334306361336632666639376237613136393364346664383238
6635363333613236626663643231326532633732333239660a306635336234633438663862633638
39633363633162646635666132363565313939306465323263366463373332386264343434353666
3635376162333834310a333565636461613836663035326262333436363861306134636266633339
63386437623930386461353331316563313763313938316263653533346133666437373065376462
30303034333665643539333638323966396330393736383439643131613562613764313265373933
65623264366639333163653963636662636339343034663833643138343265366533386463353362
35373435333265353431313665633831383038663035653135356538636638663261323861623236
64663461383236663335653936386331663438353564373238333062353430316432633231376230
34316461353035393064653161303062333438393135633633633734323238346131656432633965
62336334636436376665393531653263633963393065343863666135303739643234373038633963
37333739333966323732303163386362303530393734356132386430356535343734363063653631
66333931383664323232633261333433333262656430666636373462653634346366663438333161
30393765616437646239363466636162663063653965366538373738393530346634326531396366
343537333434663537653033303832653636
