$ANSIBLE_VAULT;1.1;AES256
61313065386434643732353239303937363439336663303335336633373163656134653432363634
6333333938383933623461626231313464643535396335640a363733343432633566663465323736
65633563346539343362646631323739366663656339303633656661653564366265663765643861
6337303836613130350a613138383637326665323132363834343761306338636233613335666436
38626234386162343835323566376336396364336335323566363964313030346435656138306432
35356466356639663161646435333962383461663234386565343964633164623132623138306364
31313664323739353532306432633634646631303064616232373763323036626632343137626535
33343936623631303937393430393138633939366639646563306434613964373962336232393831
34383232376466356637656134626536633162666565633537616236353937666433373262333535
33396363633736306636336165353433663961636531383464306132363066633834393038376138
66353462656466666266663235643639383663633535346239383661643432646663393863623563
61653864386366363166313531303764626332333736323538646238343961623561643332633135
34313437306463386631396665376436333034623533373632363439366662636136306239633632
31313864336539363630353634386335613964626336316536356437353462373431313739343461
65353035346438343136313930303031353366623132393135313164653131643134623236396563
66313132383138313234613533613934346136613335316432386561636165386266363533633933
36366130306231303738376663636532646166356533363037613033383330356234663765326164
3735383231656635626163333231623038656233396635623764
